## In this exercise we will try to re-create the decision tree from data
![](figures/play_tennis.png)

In [2]:
import pandas as pd
from sklearn import tree
#from sklearn.tree.export import export_text

In [3]:
data = pd.read_csv("data/PlayTennis.csv")

In [4]:
data

   PlayTennis   Outlook Temperature Humidity    Wind
0          No     Sunny         Hot     High    Weak
1          No     Sunny         Hot     High  Strong
2         Yes  Overcast         Hot     High    Weak
3         Yes      Rain        Mild     High    Weak
4         Yes      Rain        Cool   Normal    Weak
5          No      Rain        Cool   Normal  Strong
6         Yes  Overcast        Cool   Normal  Strong
7          No     Sunny        Mild     High    Weak
8         Yes     Sunny        Cool   Normal    Weak
9         Yes      Rain        Mild   Normal    Weak
10        Yes     Sunny        Mild   Normal  Strong
11        Yes  Overcast        Mild     High  Strong
12        Yes  Overcast         Hot   Normal    Weak
13         No      Rain        Mild     High  Strong

In [7]:
play_tennis = {'No':0, 'Yes':1}
data['PlayTennis'] = data['PlayTennis'].apply(lambda x: play_tennis[x])

In [8]:
outlook = {'Sunny':1, 'Overcast':2, 'Rain':3}
data['Outlook'] = data['Outlook'].apply(lambda x: outlook[x])

In [9]:
temp = {'Hot':1, 'Mild':2, 'Cool':3}
data['Temperature'] = data['Temperature'].apply(lambda x: temp[x])

In [10]:
hum = {'High':1, 'Normal':2}
data['Humidity'] = data['Humidity'].apply(lambda x: hum[x])

In [11]:
wind = {'Strong':1, 'Weak':2}
data['Wind'] = data['Wind'].apply(lambda x: wind[x])

In [12]:
data

    PlayTennis  Outlook  Temperature  Humidity  Wind
0            0        1            1         1     2
1            0        1            1         1     1
2            1        2            1         1     2
3            1        3            2         1     2
4            1        3            3         2     2
5            0        3            3         2     1
6            1        2            3         2     1
7            0        1            2         1     2
8            1        1            3         2     2
9            1        3            2         2     2
10           1        1            2         2     1
11           1        2            2         1     1
12           1        2            1         2     2
13           0        3            2         1     1

Train a decision tree using the data and then print the tree

*Note* You will need to change the values from string to numbers before training the tree

In [13]:
dtree = tree.DecisionTreeClassifier().fit(
    data[['Outlook', 'Temperature', 'Humidity', 'Wind']], data['PlayTennis'])

In [14]:
dtree

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [15]:
print(tree.export_graphviz(dtree) )

digraph Tree {
node [shape=box] ;
0 [label="X[2] <= 1.5\ngini = 0.459\nsamples = 14\nvalue = [5, 9]"] ;
1 [label="X[0] <= 1.5\ngini = 0.49\nsamples = 7\nvalue = [4, 3]"] ;
0 -> 1 [labeldistance=2.5, labelangle=45, headlabel="True"] ;
2 [label="gini = 0.0\nsamples = 3\nvalue = [3, 0]"] ;
1 -> 2 ;
3 [label="X[3] <= 1.5\ngini = 0.375\nsamples = 4\nvalue = [1, 3]"] ;
1 -> 3 ;
4 [label="X[0] <= 2.5\ngini = 0.5\nsamples = 2\nvalue = [1, 1]"] ;
3 -> 4 ;
5 [label="gini = 0.0\nsamples = 1\nvalue = [0, 1]"] ;
4 -> 5 ;
6 [label="gini = 0.0\nsamples = 1\nvalue = [1, 0]"] ;
4 -> 6 ;
7 [label="gini = 0.0\nsamples = 2\nvalue = [0, 2]"] ;
3 -> 7 ;
8 [label="X[3] <= 1.5\ngini = 0.245\nsamples = 7\nvalue = [1, 6]"] ;
0 -> 8 [labeldistance=2.5, labelangle=-45, headlabel="False"] ;
9 [label="X[0] <= 2.5\ngini = 0.444\nsamples = 3\nvalue = [1, 2]"] ;
8 -> 9 ;
10 [label="gini = 0.0\nsamples = 2\nvalue = [0, 2]"] ;
9 -> 10 ;
11 [label="gini = 0.0\nsamples = 1\nvalue = [1, 0]"] ;
9 -> 11 ;
12 [label="gini = 0.0\nsamples = 4\nvalue = [0, 4]"] ;
8 -> 12 ;
}